
####################################################################################
# Generated by Vivado 2017.3 built on 'Wed Oct  4 19:58:22 MDT 2017' by 'xbuild'
# Command Used: write_xdc -no_fixed_only -force {C:/Users/qigua/OneDrive/Desktop/MIPI ALL/fpga/vivado/reports/mipi_csi2_capture_fpga_head_20260519/mipi_csi2_capture_fpga_head_20260519_synth.xdc}
####################################################################################


####################################################################################
# Constraints from file : 'top_constraints.xdc'
####################################################################################

# Top-level constraint skeleton for the FPGA build entry.
#
# Vivado 2017.3 compatibility rules for this file:
# - Use plain XDC commands only.
# - Do not use if/foreach/proc or other general Tcl flow control.
# - Keep this file safe for direct parsing by older Vivado releases.
#
# This file still does not assume a concrete board pinout or IO bank voltage.
# It provides only placeholder clocks for the current FPGA wrapper top.

###############################################################################
# Timing placeholders
###############################################################################

# Default target part used by the project scripts:
# - FPGA part: xczu9eg-ffvb1156-2-e
# - Placeholder byte clock for a 1.5 Gb/s per-lane style target:
#   187.5 MHz byte clock => 5.333 ns period
# - Keep clk_sys/clk_axi/clk_ddr at 200 MHz placeholders until the final
#   board clock tree and memory interface are frozen.



###############################################################################
# Clock constraints
###############################################################################

create_clock -period 5.000 -name clk_sys [get_ports clk_sys]
create_clock -period 5.333 -name clk_byte [get_ports clk_byte]
create_clock -period 5.000 -name clk_axi [get_ports clk_axi]
create_clock -period 5.000 -name clk_ddr [get_ports clk_ddr]

set_clock_uncertainty 0.100 [get_clocks clk_sys]
set_clock_uncertainty 0.100 [get_clocks clk_byte]
set_clock_uncertainty 0.100 [get_clocks clk_axi]
set_clock_uncertainty 0.100 [get_clocks clk_ddr]

###############################################################################
# Pin placeholders
###############################################################################

# Fill these only after a real package pinout and schematic are selected.
#
# set_property PACKAGE_PIN <PIN> [get_ports clk_sys]
# set_property IOSTANDARD  <IOSTANDARD> [get_ports clk_sys]
#
# set_property PACKAGE_PIN <PIN> [get_ports rst_n]
# set_property IOSTANDARD  <IOSTANDARD> [get_ports rst_n]
#
# set_property PACKAGE_PIN <PIN> [get_ports {lane_data_0[0]}]
# set_property IOSTANDARD  <IOSTANDARD> [get_ports {lane_data_0[0]}]

###############################################################################
# CDC and reset notes
###############################################################################

# rst_n is an active-low synchronous reset in the RTL guidelines.
# Do not add asynchronous reset false paths here unless the architecture changes.
#
# clk_byte, clk_sys, clk_axi, and clk_ddr are separate domains in the spec.
# Do not add set_clock_groups blindly. Final relationship constraints must match
# the selected clocking architecture and the implemented CDC structures.


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
